### ISSUE TITLE
A 16. feladatot nem értettem

### ISSUE THREAD

**Issue by nemethkoppany** [nemethkoppany/Webfejl_OOP#1]
A **16. feladatot** nem értettem ezért nem tudtam megoldani.
`Object.setPrototypeOf(Student.prototype,` Person.prototype)

**Comment by gomszab** [comment]
javaslom a 12-tol tanulmanyozni, mert onnantol nem jo. A 20asra adott megoldasod (aminek a fele hianyzik meg sajnos), szerintem segitsegedre lehet
